### ISSUE TITLE
The nuke-boost TODO list

### ISSUE THREAD

**Issue by sherm1** [flexible-collision-library/fcl#102]
Thanks to @scpeters in #100 for this list and idea. Please submit PRs that get rid of one or more of these and then check off the ones that are done until they are all gone. This issue is also a good place to discuss problems that arise.

- [x] boost/test/unit_test.hpp
- [x] boost/filesystem.hpp
- [x] boost/timer.hpp
- [x] boost/array.hpp
- [x] boost/assert.hpp
- [x] boost/assign/list_of.hpp
- [x] boost/bind.hpp
- [x] boost/cstdint.hpp
- [x] boost/date_time/posix_time/posix_time.hpp
- [x] boost/dynamic_bitset.hpp
- [x] boost/foreach.hpp
- [x] boost/function.hpp
- [x] boost/iterator/zip_iterator.hpp
- [x] boost/math/constants/constants.hpp
- [x] boost/math/special_functions/erf.hpp
- [x] boost/math/special_functions/fpclassify.hpp
- [x] boost/noncopyable.hpp
- [x] boost/random/lagged_fibonacci.hpp
- [x] boost/random/mersenne_twister.hpp
- [x] boost/random/normal_distribution.hpp
- [x] boost/random/uniform_int.hpp
- [x] boost/random/uniform_real.hpp
- [x] boost/random/variate_generator.hpp
- [x] boost/shared_array.hpp
- [x] boost/shared_ptr.hpp
- [x] boost/thread.hpp
- [x] boost/thread/mutex.hpp
- [x] boost/unordered_map.hpp
- [x] boost/unordered_set.hpp
- [x] boost/weak_ptr.hpp

**Comment by sherm1** [comment]
I got a response from Jia @panjia1983 regarding dynamics_bitset:

>From: Jia Pan [mailto:panjia1983@gmail.com] 
Sent: Friday, March 25, 2016 10:36 AM
To: Michael Sherman <sherm@tri.global>
Subject: Re: FCL notifications?

>The morton code is used for some acceleration of multi-object collisions (Figure 2 in this paper: http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6631081). It is just one acceleration choice, and it does not hurt much if being remove -- the user can always choose other ways for acceleration. 

Not sure how to interpret that -- Jia, are you saying that if it is restricted to compile-time size then it won't be useful at all?

**Comment by jslee02** [comment]
All the boost dependencies are removed by #103, #104, #105, #108, #140, #146, #147, and #148!

Closing this issue.

**Comment by sherm1** [comment]
Yay -- look at that beautiful list of check marks! Thanks, JS and the rest of the boost-bashing team. :+1:
